const {
  Entry
} = require('../models');

const entryData = [{
    name: 'Fred',
    email: 'fred@gmail.com',
    phone: 452210918,
    sector: 'Community sector',
    post: 2000,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Sam',
    email: 'sam@gmail.com',
    phone: 452210913,
    sector: 'Disability sector',
    post: 2001,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Jack',
    email: 'jack@gmail.com',
    phone: 452210914,
    sector: 'Child protection, youth and family services',
    post: 2002,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Michael',
    email: 'michael@gmail.com',
    phone: 452210914,
    sector: 'Women’s Services',
    post: 2002,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Jennifer',
    email: 'jennifer@gmail.com',
    phone: 452210915,
    sector: 'Community and Neighbourhood Centres',
    post: 2002,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Cassandra',
    email: 'cassandra@gmail.com',
    phone: 4522109156,
    sector: 'Migrant and settlement services',
    post: 2005,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Julia',
    email: 'julia@gmail.com',
    phone: 4522109157,
    sector: 'Policy and Advocacy',
    post: 2006,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'David',
    email: 'david@gmail.com',
    phone: 4522109158,
    sector: 'Housing and homelessness',
    post: 2007,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Mark',
    email: 'mark@gmail.com',
    phone: 4522109143,
    sector: 'Mental Health',
    post: 2008,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Fabio',
    email: 'fabio@gmail.com',
    phone: 4522109129,
    sector: 'Not For Profit',
    post: 2010,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  },
  {
    name: 'Sally',
    email: 'sally@gmail.com',
    phone: 4522109112,
    sector: 'Other',
    post: 2013,
    employer: 'test company',
    years: 6,
    union: true,
    shift: true,
    personal: 60,
    annual: 25,
    long: 4.80,
  }


];

const seedEntry = () => Entry.bulkCreate(entryData);

module.exports = seedEntry;